services:
  db:
    image: postgres:15
    container_name: pulse-postgres
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pulse_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./PulseIngest.Api
      dockerfile: Dockerfile
    container_name: pulse-api
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=pulse;Username=postgres;Password=postgres
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"

volumes:
  pulse_postgres_data: